// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADXOdafSJR5aIon5i9Ncc4PtqEpwfpd6M',
    appId: '1:503358444268:web:f5c32a076385e1c6940bc9',
    messagingSenderId: '503358444268',
    projectId: 'test-d12b2',
    authDomain: 'test-d12b2.firebaseapp.com',
    databaseURL: 'https://test-d12b2-default-rtdb.firebaseio.com',
    storageBucket: 'test-d12b2.appspot.com',
    measurementId: 'G-DMFQ6TQ0RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19xKJTqMuGZu1a2vLX6LstOS3AB8T8HA',
    appId: '1:503358444268:android:74727809ad42ec2f940bc9',
    messagingSenderId: '503358444268',
    projectId: 'test-d12b2',
    databaseURL: 'https://test-d12b2-default-rtdb.firebaseio.com',
    storageBucket: 'test-d12b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDv8-aGXprwSA_zMDw3vQ3ZCB-q6zxnME',
    appId: '1:503358444268:ios:99a51e1370df46a8940bc9',
    messagingSenderId: '503358444268',
    projectId: 'test-d12b2',
    databaseURL: 'https://test-d12b2-default-rtdb.firebaseio.com',
    storageBucket: 'test-d12b2.appspot.com',
    iosBundleId: 'com.example.goog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDv8-aGXprwSA_zMDw3vQ3ZCB-q6zxnME',
    appId: '1:503358444268:ios:4a7edb285bee5f30940bc9',
    messagingSenderId: '503358444268',
    projectId: 'test-d12b2',
    databaseURL: 'https://test-d12b2-default-rtdb.firebaseio.com',
    storageBucket: 'test-d12b2.appspot.com',
    iosBundleId: 'com.example.goog.RunnerTests',
  );
}
